<a href="https://colab.research.google.com/github/DeepanshuSharma1607/tech_stuck/blob/main/dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "diabetes.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "mathchi/diabetes-data-set",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_4247/2555271029.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'diabetes-data-set' dataset.
First 5 records:    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1

In [ ]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
X=df.drop(columns=['Outcome'])
y=df['Outcome']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [ ]:
from sklearn.linear_model import LogisticRegression,Perceptron
p=LogisticRegression(max_iter=100000)
p.fit(X_train,y_train)
print(p.coef_)
print(p.intercept_)
'''
perceptron : [[ 530.     168.    -311.      13.     102.     -81.2      5.978   70.   ]]
[-149.]

logistic regression : [[ 0.06106262  0.0337888  -0.01387792  0.00474554 -0.0019446   0.10151985
   0.59002294  0.03768787]]
[-8.93569889]

'''

[[ 0.06437262  0.03409503 -0.01387901  0.00329083 -0.00180346  0.10260651
   0.62671806  0.0370955 ]]
[-9.00675402]

'\nperceptron : [[ 530.     168.    -311.      13.     102.     -81.2      5.978   70.   ]]\n[-149.]\n\nlogistic regression : [[ 0.06106262  0.0337888  -0.01387792  0.00474554 -0.0019446   0.10151985\n   0.59002294  0.03768787]]\n[-8.93569889]\n\n'

In [ ]:
from sklearn.metrics import accuracy_score
y_pred_test=p.predict(X_test)
y_pred_train=p.predict(X_train)
print('accuracy_of_training ',accuracy_score(y_pred_train,y_train))
print('accuracy_of_testing ',accuracy_score(y_pred_test,y_test))

'''
perceptron : accuracy_of_training  0.5211726384364821
accuracy_of_testing  0.5714285714285714


logistic regression :
accuracy_of_training  0.7703583061889251
accuracy_of_testing  0.7402597402597403

'''

accuracy_of_training  0.7703583061889251
accuracy_of_testing  0.7467532467532467

'\nperceptron : accuracy_of_training  0.5211726384364821\naccuracy_of_testing  0.5714285714285714\n\n\nlogistic regression :\naccuracy_of_training  0.7703583061889251\naccuracy_of_testing  0.7402597402597403\n\n'

In [ ]:
def perceptron(x,y):
  x=np.insert(x,0,1,axis=1)
  w=np.ones(x.shape[1])
  alpha=0.01
  for i in range(10000):
    j=np.random.randint(0,x.shape[0])
    y_hat=get(np.dot(x[j],w))
    # Corrected: Use .iloc for positional indexing on the Pandas Series y
    w=w+alpha*(y.iloc[j]-y_hat)*x[j]

  return w[0],w[1:]

In [ ]:
def get(x):
  return 1 if x>0 else 0

In [ ]:
intercept_,coef_=perceptron(X_train,y_train)
print(coef_,intercept_)

[10.9      0.05    -4.33     0.43    -0.7      1.6      1.25884 -0.79   ] -2.8699999999999837

In [ ]:
y_pred_train_=np.dot(X_train,coef_)+intercept_
y_pred_test_=np.dot(X_test,coef_)+intercept_

vec_get=np.vectorize(get)
y_pred_train_=vec_get(y_pred_train_)
y_pred_test_=vec_get(y_pred_test_)

print('accuracy_of_training ',accuracy_score(y_pred_train_,y_train))
print('accuracy_of_testing ',accuracy_score(y_pred_test_,y_test))

accuracy_of_training  0.6482084690553745
accuracy_of_testing  0.6493506493506493

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found

In [ ]:
def perceptron_(x,y):
  w=np.ones(x.shape[1])
  b=1
  alp=0.1
  for i in range(1000):
    j=np.random.randint(0,x.shape[0])
    x_=x.iloc[j].values
    y_=y.iloc[j]
    z=np.dot(x_,w)+b
    if z*y_<0:
      w=w+alp*y_*x_
      b=b+alp*y_*x_

  return w,b

In [ ]:
w,b=perceptron_(X,y)
w,b

(array([1., 1., 1., 1., 1., 1., 1., 1.]), 1)